# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "npm run build"
[[headers]]
  for="/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      img-src 'self' https://i.imgur.com/ https://secure.gravatar.com https://*.githubusercontent.com/u/ https://kernvalley.us https://*.kernvalley.us;
      script-src 'self' https://cdn.kernvalley.us https://cdn.polyfill.io/v3/polyfill.min.js;
      style-src 'self' https://cdn.kernvalley.us;
      connect-src 'self' https://api.github.com/users/ https://cdn.kernvalley.us https://api.openweathermap.org/data/ https://cdn.polyfill.io/v3/polyfill.min.js;
      worker-src: 'self';
      font-src 'self' https://cdn.kernvalley.us;
      media-src 'none';
      object-src: 'none';
      manifest-src 'self';
      form-action 'self';
      reflected-xss block;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;'''
# [[redirects]]
  # from = ""
  # to = ""
